Arguments: 
  /Users/sandro/.nvm/versions/node/v16.11.0/bin/node /Users/sandro/.yarn/bin/yarn.js add @types/react-virtuoso

PATH: 
  /Users/sandro/anaconda3/envs/kjoa/bin:/Users/sandro/anaconda3/condabin:/Users/sandro/.nvm/versions/node/v16.11.0/bin:/Users/sandro/.yarn/bin:/Users/sandro/.config/yarn/global/node_modules/.bin:/Users/sandro/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/share/dotnet/sdk:/usr/local/share/dotnet/sdk/3.1.100:/usr/local/MacGPG2/bin:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Postgres.app/Contents/Versions/latest/bin

Yarn version: 
  1.22.15

Node version: 
  16.11.0

Platform: 
  darwin x64

Trace: 
  Error: https://registry.npmjs.org/@types%2freact-virtuoso: Not found
      at Request.params.callback [as _callback] (/Users/sandro/.yarn/lib/cli.js:67031:18)
      at Request.self.callback (/Users/sandro/.yarn/lib/cli.js:140885:22)
      at Request.emit (node:events:390:28)
      at Request.<anonymous> (/Users/sandro/.yarn/lib/cli.js:141857:10)
      at Request.emit (node:events:390:28)
      at IncomingMessage.<anonymous> (/Users/sandro/.yarn/lib/cli.js:141779:12)
      at Object.onceWrapper (node:events:509:28)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
  # yarn lockfile v1
